<footer>
	<!--[if lte IE 9]>
		<div style="color:blue;"><a href="http://browsehappy.com/?locale=en" color="blue">Please consider getting a more up-to-date browser for the best experience of this website.</a></div>
		<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
	<![endif]-->
	<div id="noscript"><h3><noscript>Please enable JavaScript for this whole website for the best experience.</noscript></h3></div>
	<script>document.getElementById('noscript').style.display='none';</script>
	<div>
		<a href="/license.php">License</a> | <a href="/about.php">About</a> | <a href="/contact.php">Contact</a> | <a href="/sitemap.php">Sitemap</a>
	</div>
	<img src= "/images/phunlogo.png" title="My Algodoo Phun Logo" alt="BLiu1 - My Algodoo Phun Logo" />
	<p>Email me at <a href="mailto:&#x73;&#x75;&#x70;&#x70;&#x6f;&#x72;&#x74;&#x40;&#x62;&#x6c;&#x69;&#x75;&#x31;&#x2e;&#x63;&#x6f;&#x6d;&#x78;&#x61;&#x2e;&#x63;&#x6f;&#x6d;">&#x73;&#x75;&#x70;&#x70;&#x6f;&#x72;&#x74;&#x40;&#x62;&#x6c;&#x69;&#x75;1&#x2e;&#x63;&#x6f;&#x6d;&#x78;&#x61;&#x2e;&#x63;&#x6f;&#x6d;</a> .</p>
</footer>
